from typing import Self, Dict, Literal
from numbers import Number
from dominate.dom_tag import dom_tag


class dom1core(object):
    @property
    def parentNode(self) -> dom_tag: ...
    def getElementById(self, id: str) -> dom_tag: ...
    def getElementsByTagName(self, name: str) -> dom_tag: ...
    def appendChild(self, obj: dom_tag | str | Number | Dict[str | int, str | "dom_tag" | Literal[True]] ) -> Self: ...
